=begin
#Api Documentation

#Api Documentation

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.2

=end

require 'uri'

module SwaggerClient
  class MoversApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # getMovers
    # @param [Hash] opts the optional parameters
    # @option opts [String] :direction direction
    # @return [MultipleOfMovers]
    def get_movers_using_get(opts = {})
      data, _status_code, _headers = get_movers_using_get_with_http_info(opts)
      data
    end

    # getMovers
    # @param [Hash] opts the optional parameters
    # @option opts [String] :direction direction
    # @return [Array<(MultipleOfMovers, Fixnum, Hash)>] MultipleOfMovers data, response status code and response headers
    def get_movers_using_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MoversApi.get_movers_using_get ...'
      end
      # resource path
      local_var_path = '/midlands/movers/sp500/'

      # query parameters
      query_params = {}
      query_params[:'direction'] = opts[:'direction'] if !opts[:'direction'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'MultipleOfMovers')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MoversApi#get_movers_using_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
