=begin
#Api Documentation

#Api Documentation

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.2

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccountsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountsApi)
    end
  end

  # unit tests for get_all_positions_using_get
  # getAllPositions
  # @param account_id accountId
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :nonzero nonzero
  # @return [MultipleOfPosition]
  describe 'get_all_positions_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_using_get
  # getAll
  # @param [Hash] opts the optional parameters
  # @return [MultipleOfAccountInfo]
  describe 'get_all_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_port_folio_using_get
  # getPortFolio
  # @param account_id accountId
  # @param [Hash] opts the optional parameters
  # @return [Portfolio]
  describe 'get_port_folio_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_position_using_get
  # getPosition
  # @param account_id accountId
  # @param position_id positionId
  # @param [Hash] opts the optional parameters
  # @return [Position]
  describe 'get_position_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
