=begin
#Api Documentation

#Api Documentation

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.2

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::InstrumentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InstrumentsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::InstrumentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InstrumentsApi' do
    it 'should create an instance of InstrumentsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::InstrumentsApi)
    end
  end

  # unit tests for get_all_using_get1
  # getAll
  # @param [Hash] opts the optional parameters
  # @return [MultipleOfInstrumentData]
  describe 'get_all_using_get1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_splits_using_get
  # getSplits
  # @param instrument_id instrument_id
  # @param [Hash] opts the optional parameters
  # @return [MultipleOfInstrumentSplit]
  describe 'get_splits_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_using_get
  # get
  # @param instrument_id instrument_id
  # @param [Hash] opts the optional parameters
  # @return [InstrumentData]
  describe 'get_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for query_using_get1
  # query
  # @param [Hash] opts the optional parameters
  # @option opts [String] :query query
  # @return [MultipleOfInstrumentData]
  describe 'query_using_get1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
