=begin
#Api Documentation

#Api Documentation

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.2

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MarketsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MarketsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MarketsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketsApi' do
    it 'should create an instance of MarketsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MarketsApi)
    end
  end

  # unit tests for get_all_using_get2
  # getAll
  # @param [Hash] opts the optional parameters
  # @return [MultipleOfMarketData]
  describe 'get_all_using_get2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_m_arket_hours_using_get
  # getMArketHours
  # @param date date
  # @param mic mic
  # @param [Hash] opts the optional parameters
  # @return [MarketHours]
  describe 'get_m_arket_hours_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
