=begin
#Api Documentation

#Api Documentation

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.2

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::QuoteApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'QuoteApi' do
  before do
    # run before each test
    @instance = SwaggerClient::QuoteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of QuoteApi' do
    it 'should create an instance of QuoteApi' do
      expect(@instance).to be_instance_of(SwaggerClient::QuoteApi)
    end
  end

  # unit tests for get_quote_using_get
  # getQuote
  # @param symbol symbol
  # @param [Hash] opts the optional parameters
  # @return [QuoteData]
  describe 'get_quote_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_quotes_using_get
  # getQuotes
  # @param [Hash] opts the optional parameters
  # @option opts [String] :symbols symbols
  # @return [MultipleOfQuoteData]
  describe 'get_quotes_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
