=begin
#Api Documentation

#Api Documentation

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.2

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::Movers
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Movers' do
  before do
    # run before each test
    @instance = SwaggerClient::Movers.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Movers' do
    it 'should create an instance of Movers' do
      expect(@instance).to be_instance_of(SwaggerClient::Movers)
    end
  end
end
